<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LogDecoder.GUI.Avalonia</AssemblyName>
    <ApplicationIcon>Assets/favicon.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.*" />
    <PackageReference Include="Avalonia.Desktop" Version="11.*" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.*" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.7" />
    <PackageReference Include="OxyPlot.Avalonia" Version="2.1.0-avalonia11" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogDecoder.Infrastructure\LogDecoder.Infrastructure.csproj" />
    <ProjectReference Include="..\LogDecoder.Parser\LogDecoder.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Lang\Resources.en.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.en.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Lang\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Lang\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Lang\Resources.en.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.en.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
