id: 1123
name: ID_OXY
length: 1
parser: config
description: Управление содержанием кислорода
fields:
- name: OxygenPercent
  kind: Value
  byte: 0
  description: Содержание кислорода на вдохе
  unit: '%'
