id: 1184
hex: '0x4a0'
name: ID_MODE_CIVL
module: CIVL
direction: input
length: 1
setsContext:
  key: civlMode
  byte: 0
fields:
- name: Mode
  kind: Value
  byte: 0
  description: Режим работы блока
  values:
    0: ОЖИДАНИЕ
    1: РАБОТА
    2: Короткий Внутренний Тест (КВТ)
    3: Полный Внутренний Тест (ПВТ)
    4: калибровка клапана выдоха
    5: калибровка датчика кислорода на вдохе
    6: калибровка FASTOXY в капнографе бокового отведения
    7: калибровка датчиков давления
    8: проверка ЭМКВ
    9: калибровка датчика потока кислорода в СГ
    10: калибровка генератора потока
    11: генерация потока
    12: проверка утечки
    13: технологический детский режим
    14: калибровка датчика потока воздуха в СГ
    15: калибровка преобразователя поток-давление
    16: { message: АВАРИЙНЫЙ РЕЖИМ №1 (АР-1), status: Warning }
    17: { message: АВАРИЙНЫЙ РЕЖИМ №2 (АР-2), status: Warning }
    18: { message: АВАРИЙНЫЙ РЕЖИМ №3 (АР-3), status: Warning }
    19: { message: ПОЛНОСТЬЮ АВАРИЙНЫЙ РЕЖИМ (ПАР), status: Warning }
    21: замена датчика кислорода на вдохе
    22: запуск загрузчика для обновления прошивки КИВЛ
    23: Инициализация
    24: калибровка нулей датчиков давления в зависимости от температуры
    25: тест контура для режима nCPAP
description: Управление режимом работы КИВЛ
