id: 1201
name: ID_M_MV_CIVL
length: 4
parser: config
fields:
- name: MinuteVentilationTotal
  kind: Value
  bytes:
  - 0
  - 1
  unit: мл/мин
- name: MinuteVentilationMachine
  kind: Value
  bytes:
  - 2
  - 3
  unit: мл/мин
