id: 1207
name: ID_WORKTIME_CIVL
length: 4
parser: config
fields:
- name: WorkTimeFromRelease
  kind: Value
  bytes:
  - 0
  - 1
  - 2
  - 3
  description: Время наработки аппарата с момента выпуска
  unit: мин
