id: 1253
hex: '0x4e5'
name: ID_GET_OPT_SPO
module: SPO
direction: output
length: 4
parser: config
fields:
- name: PpgSampleRate
  kind: Value
  bytes:
  - 0
  - 1
  description: Частота отсчетов ФПГ
- name: AnalysisSettings
  kind: Value
  byte: 2
  description: Текущие настройки анализа
- name: Reserved
  kind: Raw
  byte: 3
  description: Резерв
description: Параметры работы модуля
