id: 1284
name: ID_VENTILATOR_SN_CIVL2
length: 4
parser: config
description: Серийный номер аппарата
fields:
- name: VentilatorSerialNumber
  kind: Value
  bytes:
  - 0
  - 1
  - 2
  - 3
  description: Серийный номер аппарата
