id: 1304
hex: '0x518'
name: ID_NCPAP_CIVL2
module: CIVL2
direction: output
length: 2
parser: config
fields:
- name: MeanNcpapPressure
  kind: Value
  bytes:
  - 0
  - 1
  description: Усредненное давление nCPAP
  unit: мм вод.ст.
description: Давление nCPAP
