id: 1451
name: ID_REAL_SPEED_MOTOR
length: 3
parser: config
description: Состояние модуля и текущая угловая скорость вращения вала ГП
fields:
- name: RealMotorSpeed
  kind: Value
  bytes:
  - 0
  - 1
  description: Текущая скорость вращения двигателя
  scale: 0.1
  unit: об/мин
- name: StatusByte
  kind: Raw
  byte: 2
  description: Статусная информация, совпадает с байтом 0 ID_STATUS_MOTOR
