protocol:
  name: Zisline CAN protocol subset
  revision: 1.0.1
  document: ТЕСН.941144.001 ИО
  canIdBits: 11
  endianness: Little
schema:
  fieldKinds:
  - Value
  - Bit
  - BitRange
  - Raw
  note: Все многобайтовые значения трактуются как little-endian, если поле явно не
    переопределяет это.
packagesPath: "[0-9]*.yaml"
packageFiles:
- 1120_id_synhro.yaml
- 1023_id_off_pwr.yaml
- 1025_id_status_pwr.yaml
- 1058_id_status_scm.yaml
- 1090_id_status_mix.yaml
- 1093_id_flow_mix.yaml
- 1104_id_stat_err_mix.yaml
- 1123_id_oxy.yaml
- 1154_id_status_capno1.yaml
- 1156_id_wave_capno1.yaml
- 1157_id_co2_data_capno1.yaml
- 1168_id_metabol_data_capno1.yaml
- 1184_id_mode_civl.yaml
- 1187_id_par1_civl.yaml
- 1188_id_par2_civl.yaml
- 1189_id_par3_civl.yaml
- 1190_id_wave_civl.yaml
- 1192_id_status_civl.yaml
- 1193_id_clbr_err_civl.yaml
- 1196_id_m_vinsp_civl.yaml
- 1197_id_m_vexp_civl.yaml
- 1198_id_m_peep_civl.yaml
- 1199_id_m_rb_civl.yaml
- 1200_id_m_pip_civl.yaml
- 1201_id_m_mv_civl.yaml
- 1202_id_m_texp_civl.yaml
- 1203_id_m_tinsp_civl.yaml
- 1204_id_m_compl_civl.yaml
- 1205_id_m_leak_civl.yaml
- 1207_id_worktime_civl.yaml
- 1219_id_status_capno2.yaml
- 1220_id_wave_capno2.yaml
- 1221_id_data_capno2.yaml
- 1223_id_voldata_capno2.yaml
- 1224_id_wave_vco2_capno2.yaml
- 1249_id_status_spo.yaml
- 1253_id_get_opt_spo.yaml
- 1284_id_ventilator_sn_civl2.yaml
- 1293_id_vexp_civl2.yaml
- 1294_id_par5_civl2.yaml
- 1296_id_status2_civl2.yaml
- 1298_id_paux_wave_civl2.yaml
- 1299_id_paux_data_civl2.yaml
- 1300_id_paux_data2_civl2.yaml
- 1304_id_ncpap_civl2.yaml
- 1345_id_out_extflow.yaml
- 1409_id_status_spo_v2_1.yaml
- 1410_id_status_spo_v2_2.yaml
- 1449_id_status_motor.yaml
- 1451_id_real_speed_motor.yaml
