//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDecoder.GUI.Avalonia.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LogDecoder.GUI.Avalonia.Lang.Resources_en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        internal static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        internal static string MenuOpenInputFolder {
            get {
                return ResourceManager.GetString("MenuOpenInputFolder", resourceCulture);
            }
        }
        
        internal static string MenuOpenOutputFolder {
            get {
                return ResourceManager.GetString("MenuOpenOutputFolder", resourceCulture);
            }
        }
        
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        internal static string SelectInputFolder {
            get {
                return ResourceManager.GetString("SelectInputFolder", resourceCulture);
            }
        }
        
        internal static string InputFolderNotSelected {
            get {
                return ResourceManager.GetString("InputFolderNotSelected", resourceCulture);
            }
        }
        
        internal static string PackageIdsForParsing {
            get {
                return ResourceManager.GetString("PackageIdsForParsing", resourceCulture);
            }
        }
        
        internal static string SelectAllPackages {
            get {
                return ResourceManager.GetString("SelectAllPackages", resourceCulture);
            }
        }
        
        internal static string StartDateTimeLabel {
            get {
                return ResourceManager.GetString("StartDateTimeLabel", resourceCulture);
            }
        }
        
        internal static string EndDateTimeLabel {
            get {
                return ResourceManager.GetString("EndDateTimeLabel", resourceCulture);
            }
        }
        
        internal static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
        
        internal static string OutputFolderNotSelected {
            get {
                return ResourceManager.GetString("OutputFolderNotSelected", resourceCulture);
            }
        }
        
        internal static string IgnoreDuplicates {
            get {
                return ResourceManager.GetString("IgnoreDuplicates", resourceCulture);
            }
        }
        
        internal static string ExcludeEmptyTimestamps {
            get {
                return ResourceManager.GetString("ExcludeEmptyTimestamps", resourceCulture);
            }
        }
        
        internal static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        internal static string SelectFolderDialogTitle {
            get {
                return ResourceManager.GetString("SelectFolderDialogTitle", resourceCulture);
            }
        }
        
        internal static string SelectingLogsFolder {
            get {
                return ResourceManager.GetString("SelectingLogsFolder", resourceCulture);
            }
        }
        
        internal static string NoLogFilesInFolder {
            get {
                return ResourceManager.GetString("NoLogFilesInFolder", resourceCulture);
            }
        }
        
        internal static string InputFolderSelectionError {
            get {
                return ResourceManager.GetString("InputFolderSelectionError", resourceCulture);
            }
        }
        
        internal static string OutputFolderSelectionError {
            get {
                return ResourceManager.GetString("OutputFolderSelectionError", resourceCulture);
            }
        }
        
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        internal static string EndBeforeStart {
            get {
                return ResourceManager.GetString("EndBeforeStart", resourceCulture);
            }
        }
        
        internal static string ExportingWait {
            get {
                return ResourceManager.GetString("ExportingWait", resourceCulture);
            }
        }
        
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        internal static string IndexingWait {
            get {
                return ResourceManager.GetString("IndexingWait", resourceCulture);
            }
        }
        
        internal static string InputFolderLabel {
            get {
                return ResourceManager.GetString("InputFolderLabel", resourceCulture);
            }
        }
        
        internal static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        internal static string CancelExport {
            get {
                return ResourceManager.GetString("CancelExport", resourceCulture);
            }
        }
        
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        internal static string ExportCancelled {
            get {
                return ResourceManager.GetString("ExportCancelled", resourceCulture);
            }
        }
    }
}
