//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDecoder.GUI.Avalonia.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LogDecoder.GUI.Avalonia.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        internal static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        internal static string MenuOpenInputFolder {
            get {
                return ResourceManager.GetString("MenuOpenInputFolder", resourceCulture);
            }
        }
        
        internal static string MenuOpenOutputFolder {
            get {
                return ResourceManager.GetString("MenuOpenOutputFolder", resourceCulture);
            }
        }
        
        internal static string MenuTrends {
            get {
                return ResourceManager.GetString("MenuTrends", resourceCulture);
            }
        }
        
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        internal static string SelectInputFolder {
            get {
                return ResourceManager.GetString("SelectInputFolder", resourceCulture);
            }
        }
        
        internal static string InputFolderNotSelected {
            get {
                return ResourceManager.GetString("InputFolderNotSelected", resourceCulture);
            }
        }
        
        internal static string PackageIdsForParsing {
            get {
                return ResourceManager.GetString("PackageIdsForParsing", resourceCulture);
            }
        }
        
        internal static string SelectAllPackages {
            get {
                return ResourceManager.GetString("SelectAllPackages", resourceCulture);
            }
        }
        
        internal static string StartDateTimeLabel {
            get {
                return ResourceManager.GetString("StartDateTimeLabel", resourceCulture);
            }
        }
        
        internal static string EndDateTimeLabel {
            get {
                return ResourceManager.GetString("EndDateTimeLabel", resourceCulture);
            }
        }
        
        internal static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
        
        internal static string OutputFolderNotSelected {
            get {
                return ResourceManager.GetString("OutputFolderNotSelected", resourceCulture);
            }
        }
        
        internal static string IgnoreDuplicates {
            get {
                return ResourceManager.GetString("IgnoreDuplicates", resourceCulture);
            }
        }
        
        internal static string ExcludeEmptyTimestamps {
            get {
                return ResourceManager.GetString("ExcludeEmptyTimestamps", resourceCulture);
            }
        }
        
        internal static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        internal static string SelectFolderDialogTitle {
            get {
                return ResourceManager.GetString("SelectFolderDialogTitle", resourceCulture);
            }
        }
        
        internal static string SelectingLogsFolder {
            get {
                return ResourceManager.GetString("SelectingLogsFolder", resourceCulture);
            }
        }
        
        internal static string NoLogFilesInFolder {
            get {
                return ResourceManager.GetString("NoLogFilesInFolder", resourceCulture);
            }
        }
        
        internal static string InputFolderSelectionError {
            get {
                return ResourceManager.GetString("InputFolderSelectionError", resourceCulture);
            }
        }
        
        internal static string OutputFolderSelectionError {
            get {
                return ResourceManager.GetString("OutputFolderSelectionError", resourceCulture);
            }
        }
        
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        internal static string EndBeforeStart {
            get {
                return ResourceManager.GetString("EndBeforeStart", resourceCulture);
            }
        }
        
        internal static string ExportingWait {
            get {
                return ResourceManager.GetString("ExportingWait", resourceCulture);
            }
        }
        
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        internal static string IndexingWait {
            get {
                return ResourceManager.GetString("IndexingWait", resourceCulture);
            }
        }
        
        internal static string IndexingCancelling {
            get {
                return ResourceManager.GetString("IndexingCancelling", resourceCulture);
            }
        }
        
        internal static string IndexingCancelled {
            get {
                return ResourceManager.GetString("IndexingCancelled", resourceCulture);
            }
        }
        
        internal static string InputFolderLabel {
            get {
                return ResourceManager.GetString("InputFolderLabel", resourceCulture);
            }
        }
        
        internal static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        internal static string CancelExport {
            get {
                return ResourceManager.GetString("CancelExport", resourceCulture);
            }
        }
        
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        internal static string ExportCancelled {
            get {
                return ResourceManager.GetString("ExportCancelled", resourceCulture);
            }
        }
        
        internal static string ExportCancelling {
            get {
                return ResourceManager.GetString("ExportCancelling", resourceCulture);
            }
        }
        
        internal static string CriticalErrorTitle {
            get {
                return ResourceManager.GetString("CriticalErrorTitle", resourceCulture);
            }
        }
        
        internal static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        internal static string MenuDebugLog {
            get {
                return ResourceManager.GetString("MenuDebugLog", resourceCulture);
            }
        }
        
        internal static string DebugLogTitle {
            get {
                return ResourceManager.GetString("DebugLogTitle", resourceCulture);
            }
        }
        
        internal static string DebugLogFilterLabel {
            get {
                return ResourceManager.GetString("DebugLogFilterLabel", resourceCulture);
            }
        }
        
        internal static string TrendsTitle {
            get {
                return ResourceManager.GetString("TrendsTitle", resourceCulture);
            }
        }
        
        internal static string TrendsScaleLabel {
            get {
                return ResourceManager.GetString("TrendsScaleLabel", resourceCulture);
            }
        }
        
        internal static string TrendsStartLabel {
            get {
                return ResourceManager.GetString("TrendsStartLabel", resourceCulture);
            }
        }
        
        internal static string TrendsBatteryLabel {
            get {
                return ResourceManager.GetString("TrendsBatteryLabel", resourceCulture);
            }
        }
        
        internal static string BatteryCharging {
            get {
                return ResourceManager.GetString("BatteryCharging", resourceCulture);
            }
        }
        
        internal static string TrendsVentilationParams {
            get {
                return ResourceManager.GetString("TrendsVentilationParams", resourceCulture);
            }
        }
        
        internal static string TrendsErrors {
            get {
                return ResourceManager.GetString("TrendsErrors", resourceCulture);
            }
        }
        
        internal static string TrendsDateNotFound {
            get {
                return ResourceManager.GetString("TrendsDateNotFound", resourceCulture);
            }
        }
        
        internal static string ScaleMinutes {
            get {
                return ResourceManager.GetString("ScaleMinutes", resourceCulture);
            }
        }
        
        internal static string ScaleSeconds {
            get {
                return ResourceManager.GetString("ScaleSeconds", resourceCulture);
            }
        }
        
        internal static string TrendsPip {
            get {
                return ResourceManager.GetString("TrendsPip", resourceCulture);
            }
        }
        
        internal static string TrendsPeep {
            get {
                return ResourceManager.GetString("TrendsPeep", resourceCulture);
            }
        }
        
        internal static string TrendsMvTotal {
            get {
                return ResourceManager.GetString("TrendsMvTotal", resourceCulture);
            }
        }
        
        internal static string TrendsMvMachine {
            get {
                return ResourceManager.GetString("TrendsMvMachine", resourceCulture);
            }
        }
        
        internal static string TrendsVt {
            get {
                return ResourceManager.GetString("TrendsVt", resourceCulture);
            }
        }
        
        internal static string TrendsRb1 {
            get {
                return ResourceManager.GetString("TrendsRb1", resourceCulture);
            }
        }
        
        internal static string TrendsRb2 {
            get {
                return ResourceManager.GetString("TrendsRb2", resourceCulture);
            }
        }
        
        internal static string TrendsCst {
            get {
                return ResourceManager.GetString("TrendsCst", resourceCulture);
            }
        }
        
        internal static string TrendsRst {
            get {
                return ResourceManager.GetString("TrendsRst", resourceCulture);
            }
        }
        
        internal static string TrendsLeak {
            get {
                return ResourceManager.GetString("TrendsLeak", resourceCulture);
            }
        }
        
        internal static string PackageDescriptionHint {
            get {
                return ResourceManager.GetString("PackageDescriptionHint", resourceCulture);
            }
        }
        
        internal static string PackageDescriptionMissing {
            get {
                return ResourceManager.GetString("PackageDescriptionMissing", resourceCulture);
            }
        }
        
        internal static string ConfigMissingTitle {
            get {
                return ResourceManager.GetString("ConfigMissingTitle", resourceCulture);
            }
        }
        
        internal static string ConfigMissingMessage {
            get {
                return ResourceManager.GetString("ConfigMissingMessage", resourceCulture);
            }
        }
        
        internal static string ConfigInvalidTitle {
            get {
                return ResourceManager.GetString("ConfigInvalidTitle", resourceCulture);
            }
        }
        
        internal static string ConfigInvalidMessage {
            get {
                return ResourceManager.GetString("ConfigInvalidMessage", resourceCulture);
            }
        }
        
        internal static string ConfigSelectTitle {
            get {
                return ResourceManager.GetString("ConfigSelectTitle", resourceCulture);
            }
        }
        
        internal static string ConfigSelectPrompt {
            get {
                return ResourceManager.GetString("ConfigSelectPrompt", resourceCulture);
            }
        }
        
        internal static string ConfigSelectOk {
            get {
                return ResourceManager.GetString("ConfigSelectOk", resourceCulture);
            }
        }
    }
}
